### ISSUE TITLE
java.lang.IllegalStateException: Reply already submitted on Android

### ISSUE THREAD

**Issue by kbokarius** [flutter-moum/flutter_open_appstore#26]
Getting the following error on Android with this simple use case:

`OpenAppstore.launch(androidAppId: "...", iOSAppId: "...);`

```
E/MethodChannel#flutter.moum.open_appstore(13237): Failed to handle method call
E/MethodChannel#flutter.moum.open_appstore(13237): java.lang.IllegalStateException: Reply already submitted
E/MethodChannel#flutter.moum.open_appstore(13237): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:139)
E/MethodChannel#flutter.moum.open_appstore(13237): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
```

**Comment by filippo-orru** [comment]
Same here
